repos:

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)

- repo: https://github.com/google/yapf
  rev: v0.40.2
  hooks:
    - id: yapf
      name: yapf (python)

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
      name: space cleanup (python)

- repo: https://github.com/hadialqattan/pycln
  rev: v2.4.0
  hooks:
    - id: pycln
      args: [--config=pycln.yaml]
      name: pycln (python)

- repo: local
  hooks:
    - id: run-main
      name: run-main
      language: system
      entry: python main.py




